["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "./"

["protostar.contracts"]
main = [
    "src/main.cairo",
]

[profile.devnet.protostar.deploy]
gateway_url="http://127.0.0.1:5050/"
chain_id=1536727068981429685321

